# Generated by Django 3.2.9 on 2023-02-07 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.PositiveSmallIntegerField(choices=[(1, 'Facebook'), (2, 'Twitter'), (3, 'Instagram'), (4, 'LinkedIn'), (5, 'Spotify'), (6, 'YouTube'), (7, 'SoundCloud'), (8, 'Pinterest'), (9, 'VK')], verbose_name='Type of Link')),
                ('link_url', models.URLField(verbose_name='URL of Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['user', 'id'],
            },
        ),
    ]
