# Generated by Django 3.2.18 on 2024-03-17 11:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import main.utilities
import main.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(choices=[('BY', 'Belarus'), ('RU', 'Russia'), ('UA', 'Ukraine')], max_length=2, primary_key=True, serialize=False, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('BYN', 'Belarusian Ruble'), ('UAH', 'Ukrainian Hryvnia')], max_length=3, primary_key=True, serialize=False, verbose_name='Code')),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Conversion rate')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(choices=[('be', 'Belarusian'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('uk', 'Ukrainian')], max_length=2, primary_key=True, serialize=False, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(help_text='Upload JPG or PNG image. Required minimum of size 500 x 650.', upload_to=main.utilities.get_magazine_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png')), main.validators.MinimumImageSizeValidator(500, 650)], verbose_name='Image')),
                ('file', models.FileField(upload_to=main.utilities.get_magazine_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))], verbose_name='File')),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published at')),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazines',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(choices=[('Brest-BY', 'Brest (BY)'), ('Minsk-BY', 'Minsk (BY)'), ('Moscow-RU', 'Moscow (RU)'), ('Saint-Petersburg-RU', 'Saint Petersburg (RU)'), ('Kyiv-UA', 'Kyiv (UA)'), ('Odesa-UA', 'Odesa (UA)')], max_length=32, primary_key=True, serialize=False, verbose_name='Code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['code'],
            },
        ),
    ]
